name: Staging

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub Deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: ${{ secrets.STAGING_URL }}
          environment: staging

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: public

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Build to S3
        run: aws s3 sync public s3://${{ secrets.STAGING_AWS_BUCKET }} --delete --metadata Header-X-Robots-Tag=none;

      - name: Create CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Update Deployment Status (Success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: http://my-app-url.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update Deployment Status (Failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: ${{ secrets.STAGING_URL }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
